import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Poppins, Montserrat, Lato, Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css";
import { Toaster } from "@/components/ui/toaster";
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const fontPoppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
});
export const fontMontserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600"],
});
export const fontLato = Lato({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "300", "400", "700", "900"],
});
export const fontOpen = Open_Sans({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const fontHeading = localFont({
  src: "../../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "dark antialiased min-h-screen bg-black font-sans font-inter ",
            fontSans.className,
            fontSans.variable,
            fontPoppins.className,
            fontPoppins.variable,
            fontMontserrat.className,
            fontMontserrat.variable,
            fontLato.className,
            fontLato.variable,
            fontOpen.className,
            fontOpen.variable,
            fontHeading.variable,
            fontHeading.className
          )}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </Providers>
  );
}
